name: Update Existing Lambda via CloudFormation

on:
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Install zip (if not already installed)
        run: sudo apt-get install zip -y

      - name: Zip Lambda code
        run: |
          zip -r lambda.zip index.js

      - name: Upload to S3
        run: aws s3 cp lambda.zip s3://myfunctionzip/

      - name: Deploy CloudFormation update
        run: |
          aws cloudformation update-stack \
          --stack-name ExistingLambdaStack \
          --template-body file://import-template.yml \
          --parameter-overrides S3Bucket=myfunctionzip S3Key=lambda.zip \
          --capabilities CAPABILITY_NAMED_IAM \
          --region ap-southeast-2
