name: Update Existing Lambda via CloudFormation

on:
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Install zip (if not already installed)
        run: sudo apt-get install zip -y

      - name: Generate timestamp
        id: time
        run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Zip Lambda code with timestamp
        run: |
          zip -r lambda-${{ steps.time.outputs.timestamp }}.zip index.js

      - name: Delete old Lambda zip from S3 (if exists)
        run: |
          aws s3 rm s3://myfunctionzip/lambda-*.zip || echo "No old zip file to delete"

      - name: Upload to S3
        run: aws s3 cp lambda-${{ steps.time.outputs.timestamp }}.zip s3://myfunctionzip/

      - name: Deploy CloudFormation update
        run: |
          aws cloudformation update-stack \
          --stack-name ExistingLambdaStack \
          --template-body file://import-template.yml \
          --parameters ParameterKey=S3Bucket,ParameterValue=myfunctionzip ParameterKey=S3Key,ParameterValue=lambda-${{ steps.time.outputs.timestamp }}.zip \
          --capabilities CAPABILITY_NAMED_IAM \
          --region ap-southeast-2
